apps/chats/urls.py
from django.urls import path

from .views import ChatListView, chat_details

app_name = "chats"

urlpatterns = [
    path("<uuid:pk>/", chat_details, name="detail"),
    path("", ChatListView.as_view(), name="list"),
]

apps/gifts/urls.py
from django.urls import path

from .views import (
    GiftCreateView,
    GiftDetailView,
    GiftListView,
    GiftManageListView,
    approve_gift,
    reject_gift,
    apply_for_gift,
    approve_gift_application,
)

app_name = "gifts"

urlpatterns = [
    # Gift's application
    path(
        "applications/<uuid:pk>/approve/",
        approve_gift_application,
        name="approve-gift-application",
    ),
    # Gifts
    path("manage/", GiftManageListView.as_view(), name="admin-list"),
    path("my-gifts/", GiftManageListView.as_view(user_only=True), name="my-gifts"),
    path("create/", GiftCreateView.as_view(), name="create"),
    path("<uuid:pk>/", GiftDetailView.as_view(), name="detail"),
    path("<uuid:pk>/approve/", approve_gift, name="approve-gift"),
    path("<uuid:pk>/reject/", reject_gift, name="reject-gift"),
    path("<uuid:pk>/apply/", apply_for_gift, name="apply-for-gift"),
    path("", GiftListView.as_view(), name="list"),
]

apps/pages/urls.py
from django.urls import path

from .views import index, about

app_name = "pages"

urlpatterns = [
    path("about-us/", about, name="about"),
    path("", index, name="index"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
]

joyful_gifting/urls.py
"""
URL configuration for the Joyful Gifting project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("apps.users.urls")),
    path("chats/", include("apps.chats.urls")),
    path("notifications/", include("apps.notices.urls")),
    path("notifications/", include("notifications.urls", namespace="notifications")),
    path("gifts/", include("apps.gifts.urls")),
    path("", include("apps.pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joyful_gifting/templates/partials/account_dropdown.html
{% load i18n %}
<li class="nav-item dropdown">
  <a class="px-2 nav-link link-body-emphasis dropdown-toggle"
     data-bs-toggle="dropdown"
     href="#"
     role="button"
     aria-expanded="false">
    {{ user.get_short_name }}
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'users:profile' %}">{% translate 'My profile' %}</a></li>
    <li><a class="dropdown-item" href="{% url 'gifts:my-gifts' %}">{% translate 'My gifts' %}</a></li>
    {% if perms.gifts.can_manage_gift %}
      <li><a class="dropdown-item" href="{% url 'gifts:admin-list' %}">{% translate 'Manage gifts' %}</a></li>
    {% endif %} 
    <li>
      <hr class="dropdown-divider">
    </li>
    <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% translate 'Logout' %}</a></li>
  </ul>
</li>

joyful_gifting/templates/partials/account_header.html
{% load i18n %}
<ul class="nav nav-underline">
  <li class="nav-item">
    <a href="{% url 'users:profile' %}" class="nav-link">{% translate 'My profile' %}</a>
  </li>
  
  <li class="nav-item">
    <a href="{% url 'account_email' %}" class="nav-link">{% translate 'Change email' %}</a>
  </li>
  
  <li class="nav-item">
    <a href="{% url 'account_change_password' %}" class="nav-link">{% translate 'Change password' %}</a>
  </li>
</ul>

joyful_gifting/templates/partials/footer.html
{% load i18n static %}
<div class="mt-auto container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">&copy; 2024, Joyful Gifting Team</p>

    <a href="{% url 'pages:index' %}"
       class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <img class="me-2" src="{% static 'logo.png' %}" width="32" height="32" alt="Joyful Gifting"/>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item">
        <a href="{% url 'pages:index' %}" class="nav-link px-2 text-body-secondary">{% trans "Home" %}</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'pages:about' %}" class="nav-link px-2 text-body-secondary">{% trans "About us" %}</a>
      </li>
    </ul>
  </footer>
</div>

joyful_gifting/templates/partials/header.html
{% load i18n static %}

<nav class="py-2 bg-body-tertiary border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item">
        <a href="{% url 'pages:index' %}" class="nav-link link-body-emphasis px-2 active" aria-current="page">
          {% trans "Home" %}
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'gifts:list' %}" class="nav-link link-body-emphasis px-2">
          {% trans "Gifts" %}
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url 'pages:about' %}" class="nav-link link-body-emphasis px-2">
          {% translate 'About us' %}
        </a>
      </li>
    </ul>

    <ul class="nav">
      {% if user.is_authenticated %}
        {% include 'partials/account_dropdown.html' %}
        <li class="nav-item">
          <a href="{% url 'account_logout' %}" class="nav-link link-body-emphasis px-2">{% trans "Logout" %}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url 'account_login' %}" class="nav-link link-body-emphasis px-2">{% trans "Login" %}</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_signup' %}" class="nav-link link-body-emphasis px-2">{% trans "Sign up" %}</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
<header class="py-3 mb-4">
  <div class="container d-flex flex-wrap align-items-center justify-content-center">
    <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
      <img class="me-2" src="{% static 'logo.png' %}" width="32" height="32" alt="Joyful Gifting"/>
      <span class="fs-5">Joyful Gifting</span>
    </a>

    <div class="mb-3 mb-lg-0 me-lg-auto">
      <a class="btn btn-primary" href="{% url 'gifts:create' %}">{% translate 'Give a gift' %}</a>
      <a class="ms-2 btn btn-light" href="{% url 'gifts:list' %}">{% translate 'Explore gifts' %}</a>
    </div>

    <div class="col-12 col-lg-auto mb-3 mb-lg-0">
      <div class="d-flex gap-1">
        <form role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        {% if user.is_authenticated %}
          <div hx-get="{% url 'notices:check' %}"
               hx-trigger="every 10s"
               hx-target="this"
               hx-swap="innerHTML">
            {% include 'notices/partials/notifications.html' %}
          </div>
          
          <div>
            <a href="{% url 'chats:list' %}" class="btn btn-light">
              <i class="bi bi-chat-square"></i>
            </a>
          </div>
        {% endif %} 
      </div>
    </div>
  </div>
</header>

joyful_gifting/templates/partials/messages.html
{% load django_bootstrap5 %}
{% bootstrap_messages %}